config/routes.rb
LifeInfoTracker::Application.routes.draw do
  resources :transactions

  resources :categories

  resources :accounts

  root to: "pages#main"
end

app/models/account.rb
class Account < ActiveRecord::Base
  validates_presence_of :name, :initial_value

  def effective_value
    initial_value - (Transaction.where(source_id: id).sum(:amount)) + 
      (Transaction.where(destination_id: id).sum(:amount))
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :category
  belongs_to :source, class_name: "Account"
  belongs_to :destination, class_name: "Account"

  def category_display
    category.nil? ? "Uncategorized" : category.name
  end

  def source_display
    source.nil? ? "-Income-" : source.name
  end

  def destination_display
    destination.nil? ? "-Expense-" : destination.name
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  http_basic_authenticate_with name: Auth::USER, password: Auth::PWD
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.order("executed_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  -if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :initial_value
    = f.text_field :initial_value
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing Accounts

%table
  %tr
    %th Name
    %th Description
    %th Initial value
    %th Effective value
    %th
    %th
    %th

  - @accounts.each do |account|
    %tr
      %td= account.name
      %td= account.description
      %td= number_to_currency account.initial_value
      %td= number_to_currency account.effective_value
      %td= link_to 'Show', account
      %td= link_to 'Edit', edit_account_path(account)
      %td= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Description:
  = @account.description
%p
  %b Initial value:
  = number_to_currency @account.initial_value

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/categories/_form.html.haml
= form_for @category do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.description
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Description:
  = @category.description

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Personal Life Info Tracker
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .topbar
      .topbar-inner
        .container
          %h3= link_to "Life Info Tracker", root_path
          %ul.nav
            %li{ class: (controller.controller_name == "pages" ? "active" : nil)}= link_to "Home", root_path
            %li{ class: (controller.controller_name == "transactions" ? "active" : nil)}= link_to "Transactions", transactions_path
            %li{ class: (controller.controller_name == "accounts" ? "active" : nil)}= link_to "Accounts", accounts_path
            %li{ class: (controller.controller_name == "categories" ? "active" : nil)}= link_to "Categories", categories_path

    .container
      - if notice
        .alert-message.block-message.success= notice
      - if alert
        .alert-message.block-message.error= alert
      
      = yield

app/views/pages/main.html.haml
%p= link_to "Accounts", accounts_path
%p= link_to "Categories", categories_path
%p= link_to "Transaction", transactions_path

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  -if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label :name
    .input= f.text_field :name
  .clearfix
    = f.label :description
    .input= f.text_area :description
  .clearfix
    = f.label :amount
    .input= f.text_field :amount
  .clearfix
    = f.label :source_id, "Source"
    .input= f.collection_select :source_id, Account.all, :id, :name, prompt: "-Income-"
  .clearfix
    = f.label :destination_id, "Destination"
    .input= f.collection_select :destination_id, Account.all, :id, :name, prompt: "-Expense-"
  .clearfix
    = f.label :executed_at
    .input= f.datetime_select :executed_at
  .clearfix
    = f.label :category_id, "Category"
    .input= f.collection_select :category_id, Category.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th Name
    %th Amount
    %th Source
    %th Destination
    %th Executed at
    %th Category
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.name
      %td= number_to_currency transaction.amount
      %td= transaction.source_display
      %td= transaction.destination_display
      %td= l transaction.executed_at
      %td= transaction.category_display
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @transaction.name
%p
  %b Description:
  = @transaction.description
%p
  %b Amount:
  = @transaction.amount
%p
  %b Source:
  = @transaction.source_display
%p
  %b Destination:
  = @transaction.destination_display
%p
  %b Executed at:
  = @transaction.executed_at
%p
  %b Category:
  = @transaction.category_display

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path